### ISSUE TITLE
Usage: How to pull dependencies with `CI_JOB_TOKEN`?

### ISSUE THREAD

**Issue by oschrenk** [gilcloud/sbt-gitlab#12]
Thank your for the plugin. I can successfully publish a jar to a project based package registry.

```
Done compiling.
[info] 	published commons_2.12 to https://gitlab.acme.de/api/v4/projects/133/packages/maven/de/acme/foobar/commons_2.12/0.4.9-SNAPSHOT/commons_2.12-0.4.9-SNAPSHOT.pom
...
```

With a valid Gitlab session in the browser I can download the file.

I am having troubles pulling that dependency from another project in the CI pipeline though.

I added 

```
enablePlugins(GitlabPlugin)
...
resolvers ++= Seq(
  "Gitlab Commons" at "https://gitlab.acme.de/api/v4/projects/133/packages/maven"
)
```

But I get

```
[error] (update) sbt.librarymanagement.ResolveException: Error downloading de.acme.foobar:commons_2.12:0.4.9-SNAPSHOT

[error]   not found: https://gitlab.acme.de/api/v4/projects/133/packages/maven/de/acme/foobar/commons_2.12/0.4.9-SNAPSHOT/commons_2.12-0.4.9-SNAPSHOT.pom
```

I could maybe inject a credentials file and convince Gitlab that way, but that would mean that I would have to create a personal api token. Is there a way to use the `CI_JOB_TOKEN` to be able to download the dependency?

**Comment by oschrenk** [comment]
I also tried `Job-Token` as a username but that doesn't work as well, probably because it is send as a username and not as a header.

**Comment by gilandose** [comment]
have you set `ThisBuild / useCoursier := false` this overrides the url handler for ivy so you have to run with ivy rather than coursier if you need to do dependency res, I thought I had that in readme will update if not

**Comment by tiagoarruda** [comment]
Hey guys,

I am having this exact same issue.
I was able to publish into gitlab package registry, but when I try to run a build of another project using that dependency the dependency is not found.
my build.sbt contains:

ThisBuild / useCoursier := false
enablePlugins(GitlabPlugin)

my plugins.sbt contain

addSbtPlugin("com.gilcloud" % "sbt-gitlab" % "0.0.6")

**Comment by oschrenk** [comment]
@tiagoarruda What error messages are you getting? Can you post them?

Your comment triggered me to also try again. When I add `ThisBuild / useCoursier := false` the dependency is somehow not resolved. sbt is complaining about imports missing, (which are from transitive dependencies from the original dependency).

**Comment by oschrenk** [comment]
I was digging deeper and it seems that the dependency resolution is not picking up the token. I tried locally first.


```
ThisBuild / useCoursier := false
resolvers ++= Seq(
  "gitlab-maven" at "https://gitlab.acme.com/api/v4/projects/123/packages/maven",
)

credentials += Credentials(Path.userHome / ".sbt" / ".credentials.gitlab")
```

I created a personal API token with `api` access and stored it

```
$ cat ~/.sbt/.credentials.gitlab
realm=gitlab-maven
host=gitlab.acme.com
user=Private-Token
password=<token>
```

I tested that the token works by issuing:

```
curl \
  --header "PRIVATE-TOKEN: <token>"   \
  https://gitlab.acme.com/api/v4/projects/123/packages/maven/com/acme/anvil/commons_2.12/0.1.0-SNAPSHOT/commons_2.12-0.1.0-SNAPSHOT.pom
```

Without the header I get a 404

Which I presume also sbt get because I get

```
[info] Executing in batch mode. For better performance use sbt's shell
[warn]  module not found: com.acme.anvil#commons_2.12;0.1.0-SNAPSHOT
...
[warn] ==== gitlab-maven: tried
[warn]   https://gitlab.badgersystems.de/api/v4/projects/133/packages/maven/com/acme/anvil/commons_2.12/0.1.0-SNAPSHOT/commons_2.12-0.1.0-SNAPSHOT.pom
...
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn]  ::          UNRESOLVED DEPENDENCIES         ::
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn]  :: com.acme.anvil#commons_2.12;0.1.0-SNAPSHOT: not found
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn]
```

**Comment by oschrenk** [comment]
I also tried adding
```
import com.gilcloud.sbt.gitlab.{GitlabCredentials,GitlabPlugin}
GitlabPlugin.autoImport.gitlabCredentials :=  Some(GitlabCredentials("Private-Token","<token>"))
```

to the `build.sbt` and it can not find the dependency. (with `curl` I can access the `pom`)

**Comment by oschrenk** [comment]
I think this ticket was confusing multiple issues. I think there is actually only one bug, for which I open another ticket.

The `README` states to use `credentials += Credentials(Path.userHome / ".sbt" / ".credentials.gitlab"),` 
I believe this is not used by the plugin.

1. Only GitlabCredentials are being injected https://github.com/gilcloud/sbt-gitlab/blob/a6e8ceeacb755bd17c9b88724831c9371903a3ad/src/main/scala/com/gilcloud/sbt/gitlab/HeaderInjector.scala#L7
2. There is no usage of https://github.com/gilcloud/sbt-gitlab/blob/a6e8ceeacb755bd17c9b88724831c9371903a3ad/src/main/scala/com/gilcloud/sbt/gitlab/GitlabCredentials.scala#L14

I created a workaround by checking the for the `CI_JOB_TOKEN` environment variable and then load the credentials manually when it doesn't exist, meaning that I am on my local environment:

```
import com.gilcloud.sbt.gitlab.{GitlabCredentials, GitlabPlugin}
GitlabPlugin.autoImport.gitlabDomain := "gitlab.acme.com"
GitlabPlugin.autoImport.gitlabCredentials := {
  sys.env.get("CI_JOB_TOKEN") match {
    // Gitlab CI pipeline
    case Some(t) =>
      Some(GitlabCredentials("Job-Token", t))
    // local machine
    case None =>
      val c = Credentials
        // realm=gitlab-maven
        // host=gitlab.acme.com
        // user=Private-Token
        // password=<TOKEN>
        .loadCredentials(Path.userHome / ".sbt" / ".credentials.gitlab")
        .left
        .map(s => new IllegalArgumentException(s))
        .toTry
        .get
      Some(GitlabCredentials(c))
  }
}
```

**Comment by oschrenk** [comment]
Besides that error (in the documentation) above, I believe the main confusions are:

1. Usage of`GitlabPlugin.autoImport.gitlabDomain := "gitlab.acme.com"` One is required to specify it when pulling dependencies.
2. Usage of `"gitlab-maven" at "https://gitlab.acme.com/api/v4/projects/123/packages/maven"` At least according to Gtilab documentation the realm is always `gitlab-maven`. So the resolver (and the credentials) need to point to the correct realm.
