### ISSUE TITLE
Release 0.0.5

### ISSUE THREAD

**Issue by oschrenk** [gilcloud/sbt-gitlab#9]
Just found the project and it seems like a good fit for us (especially since Gitlab now made the package registry free for everyone). Thank you!

I saw that there are current issues with self hosted Gitlab instances but also that https://github.com/gilcloud/sbt-gitlab/commit/78030c9c20f66f609649e15a368ceea16425b19b fixes those. 

Are you planning to release 0.0.5 with that fix soon?

**Comment by gilandose** [comment]
yeah I'll do that tonight thanks for reminding!

**Comment by gilandose** [comment]
released 0.0.5 and also 0.0.6
